INSERT INTO exam_questions
(language, question, option1, option2, option3, option4, correct_answer, difficulty)
VALUES
('cpp','Which of the following is used for input in C++?','cin','cout','printf','scanf',1,'easy'),
('cpp','Which operator is used to allocate memory in C++?','malloc','new','calloc','alloc',2,'easy'),
('cpp','What is the extension of C++ files?','.cp','.cxx','.cpp','.c++',3,'easy'),
('cpp','Who developed C++?','Dennis Ritchie','James Gosling','Bjarne Stroustrup','Guido van Rossum',3,'medium'),
('cpp','Which of the following is a correct identifier?','2value','value_2','value-2','value 2',2,'easy'),
('cpp','Which keyword is used to define a class in C++?','object','struct','class','define',3,'easy'),
('cpp','Which symbol is used to declare a pointer in C++?','*','&','#','@',1,'medium'),
('cpp','What is the default return type of functions in C++?','void','int','float','char',2,'easy'),
('cpp','Which concept allows function with same name but different arguments?','Abstraction','Polymorphism','Encapsulation','Inheritance',2,'medium'),
('cpp','Which header file includes the cout and cin objects?','<iostream>','<stdio.h>','<stdlib.h>','<conio.h>',1,'easy'),

('java','Which method is the entry point of Java program?','start()','main()','run()','init()',2,'easy'),
('java','Which keyword is used to inherit a class in Java?','this','import','extends','inherits',3,'easy'),
('java','Which of the following is not a Java primitive type?','int','float','String','boolean',3,'medium'),
('java','What is JVM?','Java Virtual Machine','Java Variable Module','Java Visual Model','None',1,'easy'),
('java','Which of these cannot be used for variable name in Java?','value$','_value','class','value1',3,'easy'),
('java','Java is a ___ language.','Compiled','Interpreted','Both','None',3,'medium'),
('java','Which exception is thrown when an array is accessed out of bounds?','NullPointerException','ArrayIndexOutOfBoundsException','NumberFormatException','IOException',2,'medium'),
('java','Which of these is used to handle exceptions?','try-catch','final','throw','import',1,'easy'),
('java','What is the size of int in Java?','2 bytes','4 bytes','8 bytes','Depends on system',2,'easy'),
('java','What does the "static" keyword mean?','Runs last','Accessible via object only','Belongs to class','None',3,'easy'),

('python','Which of the following is correct syntax for defining a function?','def func[]:','function func():','def func():','func def():',3,'easy'),
('python','What is the output of: len("Hello")?','4','5','6','None',2,'easy'),
('python','Which of these is used for comments in Python?','//','#','/* */','--',2,'easy'),
('python','What is the result of: 3 * 1**3?','1','27','3','9',2,'medium'),
('python','Which of the following data types is immutable?','List','Dictionary','Tuple','Set',3,'medium'),
('python','How do you start a loop that repeats over a list?','repeat i in list:','foreach i in list:','for i in list:','loop i list:',3,'easy'),
('python','What keyword is used to define a class in Python?','object','define','struct','class',4,'easy'),
('python','Which method is used to add an element to a list?','append()','add()','push()','insert()',1,'easy'),
('python','Which of these is not a valid Python boolean value?','TRUE','true','False','None',1,'medium'),
('python','What is the output of: print(type([]))?','<class "list">','<type list>','list()','<list>',1,'medium');
